### ISSUE TITLE
Cancelling inside callbacks

### ISSUE THREAD

**Issue by piotrmurach** [piotrmurach/finite_machine#45]
@craiglittle Cancelling inside callbacks is buggy, i.e. returning integer matching `CANCELLED` halts the callbacks stack. Which leads me to think, that either the `CANCELLED` should be a unique value or when callbacks evaluate to `false` the stack is halted. Any thoughts?

**Comment by craiglittle** [comment]
Yeah, I've always thought the use of an integer to signal a cancellation was pretty suboptimal and risky given that the return value of a callback could very easily inadvertently collide with it.

I was thinking this could be a good use case of `throw`/`catch`. Perhaps have a method that users could call when they want to halt callbacks that triggers the `throw`. If that isn't feasible, switching to a unique value makes a lot of sense.

**Comment by peter-murach** [comment]
Interesting, not sure whether `throw/catch` is feasible as things stand, but I like the idea, reminds me `sinatra` framework `:halt` symbol to mark request stop. Does the idea of `boolean` implicit return appeal to you?

**Comment by craiglittle** [comment]
Using a Boolean still seems a bit shaky. I'd really prefer some kind of explicit method call.
