### ISSUE TITLE
Setting target that responds to to_hash

### ISSUE THREAD

**Issue by JonPugsley** [piotrmurach/finite_machine#56]
### Describe the problem

I am using [Sequel](https://github.com/jeremyevans/sequel) models as a target for FiniteMachine.  The trouble is that when I initialize the finite_machine object ruby recognizes the to_hash method (I believe introduced by the json_serializer plugin) and puts the model's values into **options instead of putting the model itself into *args

This would be an issue for anything that Ruby recognizes as a hash, not just Sequel models.

### Steps to reproduce the problem

```
my_model = MyModel.create(a: 1, b: 2)
my_machine = FiniteMachine.new(my_model) do
            # etc.
end
my_machine.target == my_model # false
```

### Workaround

I'm setting `my_machine.env.target = my_model`  immediately after creating the machine.

### Possible Fixes

Allow FiniteMachine.new(target: my_model) ?
my_machine.set_target(target) method ?
Warn if there are keys in **options that aren't recognized ?

### Describe your environment

* OS version: Windows 10
* Ruby version: ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]

**Comment by piotrmurach** [comment]
Hi Jonathan,

Thanks for using `finite_machine` in your project. 🙏 

This is a great issue report that made this fix a breeze. I changed it so that your code should work by passing target to the `new` call without the need for an explicit target assignment. Will release `v0.12.1` shortly.
