### ISSUE TITLE
Message Queue Spec sometimes hangs on jruby

### ISSUE THREAD

**Issue by ahorek** [piotrmurach/finite_machine#64]
### Describe the problem
a random problem, message queue spec sometimes hangs on JRuby, but not always
https://github.com/piotrmurach/finite_machine/blob/master/spec/unit/message_queue_spec.rb

### Steps to reproduce the problem
travis

### Actual behavior
it just hangs the build, no exception

### Expected behavior
it shouldn't hang

### Describe your environment
travis / jruby-9.2.1.1 and jruby-head

**Comment by piotrmurach** [comment]
Do you have time to debug?

**Comment by ahorek** [comment]
I found the problem, take a look.
