### ISSUE TITLE
[ Feature Request ] Handling For Multiple State Machines

### ISSUE THREAD

**Issue by LWFlouisa** [piotrmurach/finite_machine#68]
I understand the basics of creating state machines, although what I'm noticing is a state machine for one state machine. In some of the stuff I do, I might have three different states to check for. Is there currently a way to implement this in the normal way, or should I just approach it like I have been:

Create three classes in a module. Within each class have three self referenced methods. In each method, create a state machine that detect the state for different "method states", and point to each defined method state. For simple stuff this is fine, but for more complex things, this can get kind of complicated.

This is less an issue with a specific algorithm, and more something I'd like to do: have handling for different states for different parts of the system. For example, per analogy I used:

~~~
Fold paper air plane.
Check if paper air plane soars.
If paper air planes is able to fly, keep model type in data model.
Else if paper air plane crashes, restart algorithm with different folded model.
Repeat until working plane model is found.
~~~

Granted this is an evolutionary model in a different sense than is found in Machine Learning. But each model would theoretically have its own state machine.

**Comment by piotrmurach** [comment]
Hi Sarah,

Thanks for using `finite_machine`.

Would [choice pseudostate](https://github.com/piotrmurach/finite_machine#39-choice-pseudostates) help?

**Comment by LWFlouisa** [comment]
I can definitely look into it! But yea I'm finding it a real life saver in terms of pointing to different methods / functions.

**Comment by piotrmurach** [comment]
Glad this resolved your issue. I'd say let's close this issue and if you come across anything please open a new one. I'd also encourage you to read through the readme as I tried to document all the methods and some useful usage examples.
