### ISSUE TITLE
Errors with Ruby 3.1.2

### ISSUE THREAD

**Issue by ghn** [piotrmurach/finite_machine#75]
### Describe the problem

Lots of warnings triggered when used with ruby 3.1.2

### Steps to reproduce the problem

With ruby 3.1.2

```
bundle exec rspec
```

### Actual behaviour

Error:

> lib/finite_machine/observer.rb:22:in `block in cleanup_callback_queue': undefined local variable or method `callback_queue' for FiniteMachine::Observer:Class (NameError)

### Expected behaviour

Specs pass without warnings

### Describe your environment

* OS version: osx 12
* Ruby version: 3.1.2
* FiniteMachine version: `master`

**Comment by ghn** [comment]
Related PR https://github.com/piotrmurach/finite_machine/pull/74

**Comment by dup2** [comment]
Would be nice to fix this and release, it is not usable on ruby 3.1+ otherwise
