### ISSUE TITLE
Transition does not happen if any_state is used in the definition.

### ISSUE THREAD

**Issue by domokos** [piotrmurach/finite_machine#76]
### Describe the problem

Transition does not happen if any_state is used in the definition 

### Steps to reproduce the problem

```ruby
class MySM < FiniteMachine::Definition

    # Does not work - definition accepted but blocks transition
    event :shouldturnon, from: any_state, to: :on

    # These work fine
    event :turnson, to: :on
    event :init, none: :off

    # Log state transitions
    on_before do |event|
        if event.from != event.to
            puts 'Working state change from '\
                "#{event.from} to #{event.to}" 
        else
            puts 'Impossible state change from '\
                "#{event.from} to #{event.to}"
        end
    end

    on_enter(:off) do |event|
      puts 'Off fired OK'
    end

    on_enter(:on) do
      puts 'This is never triggered if any_state is used in definition'
    end

  end

  mymachine = MySM.new

  #Works
  mymachine.init

  #Does not work
  mymachine.shouldturnon

  #Same thing works
  mymachine.turnson
```

### Actual behaviour

Transition does not happen if any_state is used  in the from definition

### Expected behaviour

Transition should  happen

### Describe your environment

* OS version: ubuntu 22.04, armbian 22.08
* Ruby version: 3.0.2
* FiniteMachine version: 0.14.0

This worked fine with earlier ruby/finite_machine where I used the 

event :turnoff, any: :off

notation. Bit me when I upgraded.

**Comment by piotrmurach** [comment]
Hi 👋 

Thank you for this issue report.

I can confirm that `any_state` works when a finite machine is created with the `new`. So the following works fine:

```ruby
fsm = FiniteMachine.new do
  initial :green
  event :slow, any_state => :yellow
  event :stop, :yellow => :red
end
fsm.slow
fsm.current # => :yellow
```

When it fails is when using the `define` or class definition for a finite machine:

```ruby
FSM = FiniteMachine.define do
  initial :green
  event :slow, any_state => :yellow
  event :stop, :yellow => :red
end
fsm = FSM.new
fsm.slow
fsm.current # => :green
```

The temporary fix is to use the `FiniteMachine::ANY_STATE` directly:

```ruby
FSM = FiniteMachine.define do
  initial :green
  event :slow, FiniteMachine::ANY_STATE => :yellow
  event :stop, :yellow => :red
end
fsm = FSM.new
fsm.slow
fsm.current # => :green
```

The issue is that the `any_state` and `any_event` are converted to `Proc` objects when called within `define` block. I'll provide a fix shortly.
